#pragma once

#include <stdbool.h>

typedef enum {
    APPROVAL_TRANSFER,
    APPROVAL_SIMPLE_TRANSACTION,
    APPROVAL_WITNESSCREATE_TRANSACTION,
    APPROVAL_WITNESSUPDATE_TRANSACTION,
    APPROVAL_ACCOUNTCREATE_TRANSACTION,
    APPROVAL_ACCOUNTUPDATE_TRANSACTION,
    APPROVAL_SETACCOUNTID_TRANSACTION,
    APPROVAL_CLEARABI_TRANSACTION,
    APPROVAL_UPDATESETTING_TRANSACTION,
    APPROVAL_UPDATEENERGYLIMIT_TRANSACTION,
    APPROVAL_PROPOSALCREATE_TRANSACTION,
    APPROVAL_PROPOSALAPPROVE_TRANSACTION,
    APPROVAL_PROPOSALDELETE_TRANSACTION,
    APPROVAL_PERMISSION_UPDATE,
    APPROVAL_EXCHANGE_CREATE,
    APPROVAL_EXCHANGE_TRANSACTION,
    APPROVAL_EXCHANGE_WITHDRAW_INJECT,
    APPROVAL_WITNESSVOTE_TRANSACTION,
    APPROVAL_FREEZEASSET_TRANSACTION,
    APPROVAL_UNFREEZEASSET_TRANSACTION,
    APPROVAL_WITHDRAWBALANCE_TRANSACTION,
    APPROVAL_SIGN_PERSONAL_MESSAGE,
    APPROVAL_CUSTOM_CONTRACT,
    APPROVAL_SHARED_ECDH_SECRET,
    APPROVAL_VERIFY_ADDRESS,
    APPROVAL_FREEZEASSETV2_TRANSACTION,
    APPROVAL_UNFREEZEASSETV2_TRANSACTION,
    APPROVAL_DELEGATE_RESOURCE_TRANSACTION,
    APPROVAL_UNDELEGATE_RESOURCE_TRANSACTION,
    APPROVAL_WITHDRAWEXPIREUNFREEZE_TRANSACTION,
    APPROVAL_CANCELALLUNFREEZEV2_TRANSACTION,
    APPROVAL_UPDATEBROKERAGE_TRANSACTION,
    APPROVAL_SIGN_TIP72_TRANSACTION,
} ui_approval_state_t;

void ux_flow_display(ui_approval_state_t state, bool warning);
void ui_review_menu_cleanup(void);
