#pragma once

#include <stdbool.h>

typedef enum {
    APPROVAL_TRANSFER,
    APPROVAL_SIMPLE_TRANSACTION,
    APPROVAL_WITNESSCREATE_TRANSACTION,
    APPROVAL_PERMISSION_UPDATE,
    APPROVAL_EXCHANGE_CREATE,
    APPROVAL_EXCHANGE_TRANSACTION,
    APPROVAL_EXCHANGE_WITHDRAW_INJECT,
    APPROVAL_WITNESSVOTE_TRANSACTION,
    APPROVAL_FREEZEASSET_TRANSACTION,
    APPROVAL_UNFREEZEASSET_TRANSACTION,
    APPROVAL_WITHDRAWBALANCE_TRANSACTION,
    APPROVAL_SIGN_PERSONAL_MESSAGE,
    APPROVAL_CUSTOM_CONTRACT,
    APPROVAL_SHARED_ECDH_SECRET,
    APPROVAL_VERIFY_ADDRESS,
    APPROVAL_FREEZEASSETV2_TRANSACTION,
    APPROVAL_UNFREEZEASSETV2_TRANSACTION,
    APPROVAL_DELEGATE_RESOURCE_TRANSACTION,
    APPROVAL_UNDELEGATE_RESOURCE_TRANSACTION,
    APPROVAL_WITHDRAWEXPIREUNFREEZE_TRANSACTION,
    APPROVAL_SIGN_TIP72_TRANSACTION,
    APPROVAL_SIGN_EXTERNAL_PLUGIN_CUSTOM_CONTRACT,
} ui_approval_state_t;

void ux_flow_display(ui_approval_state_t state, bool warning);
