/*******************************************************************************
 *   Tron Ledger Wallet
 *   (c) 2022 Ledger
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 ********************************************************************************/

#pragma once

typedef enum {
    APPROVAL_TRANSFER,
    APPROVAL_SIMPLE_TRANSACTION,
    APPROVAL_WITNESSCREATE_TRANSACTION,
    APPROVAL_WITNESSUPDATE_TRANSACTION,
    APPROVAL_ACCOUNTCREATE_TRANSACTION,
    APPROVAL_ASSETISSUE_TRANSACTION,
    APPROVAL_PARTICIPATEASSETISSUE_TRANSACTION,
    APPROVAL_UNFREEZETRC10_TRANSACTION,
    APPROVAL_UPDATEASSET_TRANSACTION,
    APPROVAL_ACCOUNTUPDATE_TRANSACTION,
    APPROVAL_SETACCOUNTID_TRANSACTION,
    APPROVAL_CREATESMARTCONTRACT_TRANSACTION,
    APPROVAL_CLEARABI_TRANSACTION,
    APPROVAL_UPDATESETTING_TRANSACTION,
    APPROVAL_UPDATEENERGYLIMIT_TRANSACTION,
    APPROVAL_PROPOSALCREATE_TRANSACTION,
    APPROVAL_PROPOSALAPPROVE_TRANSACTION,
    APPROVAL_PROPOSALDELETE_TRANSACTION,
    APPROVAL_PERMISSION_UPDATE,
    APPROVAL_EXCHANGE_CREATE,
    APPROVAL_EXCHANGE_TRANSACTION,
    APPROVAL_EXCHANGE_WITHDRAW_INJECT,
    APPROVAL_WITNESSVOTE_TRANSACTION,
    APPROVAL_FREEZEASSET_TRANSACTION,
    APPROVAL_UNFREEZEASSET_TRANSACTION,
    APPROVAL_WITHDRAWBALANCE_TRANSACTION,
    APPROVAL_SIGN_PERSONAL_MESSAGE,
    APPROVAL_CUSTOM_CONTRACT,
    APPROVAL_SHARED_ECDH_SECRET,
    APPROVAL_VERIFY_ADDRESS,
    APPROVAL_FREEZEASSETV2_TRANSACTION,
    APPROVAL_UNFREEZEASSETV2_TRANSACTION,
    APPROVAL_DELEGATE_RESOURCE_TRANSACTION,
    APPROVAL_UNDELEGATE_RESOURCE_TRANSACTION,
    APPROVAL_WITHDRAWEXPIREUNFREEZE_TRANSACTION,
    APPROVAL_CANCELALLUNFREEZEV2_TRANSACTION,
    APPROVAL_UPDATEBROKERAGE_TRANSACTION,
    APPROVAL_SIGN_TIP72_TRANSACTION,
} ui_approval_state_t;

void ux_flow_display(ui_approval_state_t state, bool warning);
void ui_review_menu_cleanup(void);
